[target.thumbv6m-none-eabi]
runner = "probe-rs run --preverify --chip STM32G030F6"
rustflags = [
    "-C", "link-arg=--nmagic",
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Tdefmt.x",
]

[env]
DEFMT_LOG = "info"

[alias]
run-motion = "run --bin motion --target thumbv6m-none-eabi"
build-motion = "build --bin motion --target thumbv6m-none-eabi"
run-no-motion = "run --bin no_motion --target thumbv6m-none-eabi"
build-no-motion = "build --bin no_motion --target thumbv6m-none-eabi"
run-stream = "run --bin stream --target thumbv6m-none-eabi"
build-stream = "build --bin stream --target thumbv6m-none-eabi"
run-self-test = "run --bin self_test --target thumbv6m-none-eabi"
build-self-test = "build --bin self_test --target thumbv6m-none-eabi"
run-steps = "run --bin steps --target thumbv6m-none-eabi"
build-steps = "build --bin steps --target thumbv6m-none-eabi"
run-tap = "run --bin tap --target thumbv6m-none-eabi"
build-tap = "build --bin tap --target thumbv6m-none-eabi"
run-orientation = "run --bin orientation --target thumbv6m-none-eabi"
build-orientation = "build --bin orientation --target thumbv6m-none-eabi"
run-flat = "run --bin flat --target thumbv6m-none-eabi"
build-flat = "build --bin flat --target thumbv6m-none-eabi"
run-significant-motion = "run --bin significant_motion --target thumbv6m-none-eabi"
build-significant-motion = "build --bin significant_motion --target thumbv6m-none-eabi"
run-tilt = "run --bin tilt --target thumbv6m-none-eabi"
build-tilt = "build --bin tilt --target thumbv6m-none-eabi"
run-alt-config = "run --bin alt_config --target thumbv6m-none-eabi"
build-alt-config = "build --bin alt_config --target thumbv6m-none-eabi"
